-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2016-11-29 14:48:11.019
-- Source database is: C:\Users\Admin\git\FantasyFootball\nflDB
-- Connection URL is: jdbc:derby:C:\Users\Admin\git\FantasyFootball\nflDB
-- Specified schema is: APP
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."WEEKLYTEAMS" ("PLAYERID" INTEGER NOT NULL, "FANTASYTEAMID" INTEGER NOT NULL, "WEEK" INTEGER NOT NULL);

CREATE TABLE "APP"."FANTASYTEAMS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "USERNAME" VARCHAR(50) NOT NULL, "FANTASYMASCOT" VARCHAR(100) NOT NULL);

CREATE TABLE "APP"."PLAYERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "FNAME" VARCHAR(50) NOT NULL, "LNAME" VARCHAR(50) NOT NULL, "POSITION" VARCHAR(10) NOT NULL, "POSITIONRANKING" INTEGER NOT NULL, "NFLTEAM" VARCHAR(50) NOT NULL);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "APP"."WEEKLYTEAMS" ADD CONSTRAINT "SQL161128153209451" PRIMARY KEY ("PLAYERID", "FANTASYTEAMID", "WEEK");

ALTER TABLE "APP"."FANTASYTEAMS" ADD CONSTRAINT "SQL161128153209440" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PLAYERS" ADD CONSTRAINT "SQL161128153209391" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "APP"."WEEKLYTEAMS" ADD CONSTRAINT "SQL161128153209452" FOREIGN KEY ("PLAYERID") REFERENCES "APP"."PLAYERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."WEEKLYTEAMS" ADD CONSTRAINT "SQL161128153209453" FOREIGN KEY ("FANTASYTEAMID") REFERENCES "APP"."FANTASYTEAMS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------------------------
-- DDL Statements for checks
-- ----------------------------------------------

ALTER TABLE "APP"."WEEKLYTEAMS" ADD CONSTRAINT "SQL161128153209450" CHECK (week >= 1 AND week <= 5);

ALTER TABLE "APP"."PLAYERS" ADD CONSTRAINT "SQL161128153209390" CHECK (positionRanking >= 0);

